version: "3"

services:
  app:
    build:
      context: ./app
    container_name: react-app
    restart: always
    expose:
      - "80"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c"
    command: >
      "trap exit TERM;
       while :; do sleep 6h & wait $${!}; certbot renew; done"

volumes:
  certbot-etc:
  certbot-var:
