name: CI/CD - React Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  build-push-restart:
    runs-on: [self-hosted, Linux, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nishans0/react-portfolio:latest

      - name: Restart deployment to pull latest image
        run: |
          kubectl rollout restart deployment/react-portfolio
          kubectl rollout status deployment/react-portfolio
